### ISSUE TITLE
curl dependancy

### ISSUE THREAD

**Issue by dmytrolevchenko** [saltstack-formulas/gerrit-formula#1]
hello,

i've tried to use formula under Ubuntu 12.04 Vagrant image (hashicorp/precise64), and i failed to download .war file due to curl absence.

i've added curl package dependency - and now it works fine for me. i wonder if such a fix is good and appropriate?

thanks for formula!

**Comment by envintus** [comment]
Wget is more common than curl is with regards to OOTB availability. In pull request #2 I changed the war file download to use wget.

**Comment by gravyboat** [comment]
Closing since #2 is merged.
